config/routes.rb
Rails.application.routes.draw do
	root 'users#welcome'

	get "/auth/github/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", as: "sign_out"
  get "/signin" => "sessions#new", as: "sign_in"

  resources :users, only: [:welcome, :new, :create, :destroy]

  resources :articles, only: [:index, :new]
  post "/articles" => "articles#create", as: "create_article"

  resources :upvotes, only: [:create]
  resources :goals, only: [:new, :create, :update, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :upvotes
	belongs_to :user
	validates :url, presence: {message: "Please enter the article URL."}, url: {message: "Please enter a valid URL."}
	# scope :order_by_votes, ->{ joins(:upvotes).select('articles.title, 
	# 	articles.description,
	# 	articles.user_id,
	# 	articles.url,
	# 	articles.id,
	# 	sum(upvotes.vote) as vote_count').group('articles.id').order('vote_count desc') }

	def positive_votes
		upvotes.where(vote: true)
	end

	def positive_votes_count
		positive_votes.count
	end

	def self.sort_positive_votes
		joins(:upvotes).where('upvotes.vote = true').group('articles.id').order('count(upvotes.vote) asc, created_at desc')
	end

	def self.sort_negative_votes
		joins(:upvotes).where('upvotes.vote = false').group('articles.id').order('count(upvotes.vote) asc, created_at desc')
	end
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/upvote.rb
class Upvote < ApplicationRecord
	belongs_to :user
	belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
	has_many :upvotes
	has_many :goals, dependent: :destroy
	has_many :upvotes, through: :articles

	def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth[:info][:name]
      user.email = auth[:info][:email]
      user.avatar = auth[:info][:image]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	helper_method def logged_in?
	  !!current_user #double negation to convert to boolean
	end

	helper_method def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] #memoized
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    render partial: "index"
  end

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	@article.user_id = current_user.id
  	if @article.save
      @user_articles = current_user.articles.count
  		respond_to do |format|
				format.html { redirect_to root_url }
 				format.js
 			end
 		else
 			flash[:danger] = @article.errors.values.flatten.first
 			respond_to do |format|
 				format.html { redirect_to root_url }
 				format.js
 			end
 		end
  end

  

  private

  def article_params
  	params.require(:article).permit(:title, :url, :description)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :new_goal, only: [:new, :create]
  before_action :set_goal, only: [:update]

  def new
  end

  def create
    @goal.user_id = current_user.id
    @goal.content = params[:goal][:content]
    @goal.size = params[:goal][:size]
    @goal.save
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def index
    @goals = current_user.goals
    render partial: "index", locals: {:@goals => @goals}
  end

  def update
    @goal.toggle(:completion)
    @goal.save

    @goals_count = ((current_user.goals.where(completion: true).count.to_f)/(((current_user.created_at.to_date)..(Date.today)).to_a.count)).round(1)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

  def new_goal
    @goal = Goal.new
  end

  def set_goal
    @goal = Goal.find(params[:goal][:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_with_omniauth(auth_hash)
	  if @user
     session[:user_id] = @user.id
     redirect_to root_url
	  else
     redirect_to root_url
	  end
	end

	def destroy
		session[:user_id] = nil
    redirect_to sign_in_path
	end

	protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController

  def create
  	@article = Article.find(params[:article_id])
  	@vote = Upvote.find_or_initialize_by(user_id: current_user.id, article_id: params[:article_id])
		
		if @vote.new_record? 
			@vote.vote = true
		else
			@vote.toggle(:vote)
		end
	 	@vote.save

	 	@count = 0
    current_user.articles.each { |a| @count += a.upvotes.where(vote: true).count }
    
    @positive = @article.positive_votes_count.to_s

	 	respond_to do |format|
	 		format.js 
      format.html { redirect_to root_path }
    end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

	def welcome
    if current_user.nil?
      redirect_to sign_in_path
    else
      set_user

      @articles = Article.all

      @goals = current_user.goals.all
      @goal = Goal.new

      # Goals Count
      @goals_count = ((current_user.goals.where(completion: true).count.to_f)/(((current_user.created_at.to_date)..(Date.today)).to_a.count)).round(1)

      # Articles Count
      @user_articles = current_user.articles.count

      # Upvote Count
      @count = 0
      current_user.articles.each { |a| @count += a.upvotes.where(vote: true).count }
    end
	end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  def method_name
    start_of_day = self.beginning_of_day
    end_of_day = self.end_of_day
    completed_goals_a_day = Goal.where(created_at: start_of_day .. end_of_day, completion: true).count
    goals_a_day = Goal.where(created_at: start_of_day .. end_of_day).count
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles.html.erb
 <div class="article">
    <p><strong><%= article.user.name %> posted:</strong></p>
    <p><%= article.title %></p>
    <p><%= article.description %></p>
    <p><a href="<%= article.url %>" target="_blank"><%= article.url %></a></p>
    <% if article.upvotes.where(user_id: current_user.id).exists? && article.upvotes.find_by(user_id: current_user.id).vote == true %>
    	<%= button_to "#{article.positive_votes_count} Downvote", upvotes_path(article_id: article), id: "vote-button-#{article.id}", class: "downvote btn btn-danger", remote: true %>
    <% else %>
    	<%= button_to "#{article.positive_votes_count} Upvote", upvotes_path(article_id: article), id: "vote-button-#{article.id}", class: "upvote btn btn-primary", remote: true %>
    <% end %>
</div>

<hr class="style1">

app/views/articles/_articles_count.html.erb
<h1 id="a-count-number"><%= @user_articles %></h1>
<p>Total number of articles shared</p>

app/views/articles/_form.html.erb
<div id="new-article-form">
<%= form_for :article, url: articles_path, remote: true do |form| %>
	<%= form.text_field :url, placeholder: 'Article URL' %>
	<br>
	<%= form.text_field :title, placeholder: 'Article Title' %>
	<br>
	<%= form.text_field :description, placeholder: 'Description' %>
	<br>
	<%= form.submit %>
<% end %>
</div>

app/views/articles/_index.html.erb
<% Article.sort_positive_votes.each do |article| %>
  <%= render 'articles/articles', article: article %>
<% end %>
<% Article.sort_negative_votes.each do |article| %>
  <%= render 'articles/articles', article: article %>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/create.js.erb
// if save
<%if @article.save %>
	$('#new-article-form').remove();
	$('#new_article').show();
	$('.article-feed').prepend("<%= j render 'articles/articles', article: @article %>");
<%else%>
// if error
	$('.flashes').html("<%= j render 'layouts/flashes' %>");
<%end%>

// update articles count
$('#a-count-number').text("<%= @user_articles %>")

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/new.js.erb
$('#new_article').hide().after('<%= j render("form") %>')

app/views/goals/_goals.html.erb
<div class="g-completion">
  <% if g.completion? %>
    <strike><%= g.size %><%= "   " %><%= g.content %></strike>
  <% else %>
      <%= g.size %><%= "   " %><%= g.content %>
  <% end %>
</div>
<p>
  <%= form_for g, url: goal_path(g.id), remote: true do |f| %>
    <%= f.hidden_field (:id) %>
    <%= f.hidden_field (:completion) %>
    <%= f.submit %>
  <% end %>
</p>

app/views/goals/_goals_count.html.erb
<h1 id="g-count-number"><%= @goals_count %></h1>
<p>Avg number of goals achieved per day</p>

app/views/goals/_goals_form.html.erb
<%= form_for @goal, url: goals_path, remote: true do |f| %>
  <%= f.text_field :content, placeholder: "Enter your goal"  %>
  <%= f.select :size, ["Big", "Medium", "Small"] %>
  <%= f.submit %>
<% end %>

app/views/goals/_index.html.erb
<% @goals.where("created_at >= ?", Time.zone.now.beginning_of_day).order("completion ASC, updated_at DESC").each do |g| %>
  <%= render 'goals/goals', g: g %>
<% end %>

app/views/goals/create.js.erb
$('form').trigger("reset");
$('.goal-feed').prepend("<%= j render 'goals/goals', g: @goal %>");

app/views/goals/update.js.erb
$('.goal-feed').load('/goals');
// Update goals completed stats
$('#g-count-number').text('<%= @goals_count %>');

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| -%>
  <div class="alert alert-<%= key %> fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close" style="">&times;</a><%=h value %>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.fontawesome.com/e51598acc8.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_quotes.html.erb
<div id="content-box" class="container-fluid">
  <h3 class="content">Click joke to generate joke, or quote to generate a random quote.</h3>
</div>

<a id="get-joke"><button class="btn btn-default">Joke</button></a>
<a id="get-quote"><button class="btn btn-default">Quote</button></a>

app/views/quotes/index.html.erb
<div id="content-box" class="container-fluid">
  <h3 class="content">Click joke to generate joke, or quote to generate a random quote.</h3>
</div>

<a id="get-joke"><button class="btn btn-default">Joke</button></a>
<a id="get-quote"><button class="btn btn-default">Quote</button></a>

<script>

app/views/upvotes/_downvote_button.html.erb
<%= form_for upvote do |f| %>
	<%= f.hidden_field :article_id, value: upvote.article.id %>
	<%= f.submit "Downvote", id: "downvote-button", class: "btn btn-danger" %>
<% end %>

app/views/upvotes/_upvote_button.html.erb
<%= form_for upvote do |f| %>
	<%= f.hidden_field :article_id, value: upvote.article.id %>
	<%= f.submit "Upvote", id: "upvote-button", class: "btn btn-primary" %>
<% end %>

app/views/upvotes/_upvotes_count.html.erb
<h1 id="u-count-number"><%= @count %></h1>	
<p>Total number of upvotes received for articles</p>

app/views/upvotes/create.html.erb
<h1>Upvotes#create</h1>
<p>Find me in app/views/upvotes/create.html.erb</p>

app/views/upvotes/create.js.erb
$('#u-count-number').text('<%= @count %>');
$('.article-feed').load('/articles');

app/views/users/_snake.html.erb
<div class="snake-game">

	<div class="wrapper">
		<div id="game-box"><div class="food"></div><div class ="snake" id="snake-head"></div><div class="snake" id="snake-body-1"></div><div class="snake" id="snake-body-2"></div></div>
	</div>

	<button class="start-game">
		  Play
	</button>

	<button class="restart-game">
		  Restart
	</button>

	<button class="score-board">
		<span class="score-count"> 0 </span>
	</div>

	<button class="super-food-timer">
		100
	</button>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render form %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/welcome.html.erb
<div class="navbar">
  <button class="play-snake">
    STASH
  </button>
  <%= button_to "Log out", sign_out_path, class: "logout-button nav-button", method: :get %>
</div>

<div class="flashes">
	<%= render 'layouts/flashes' %>
</div>

<div class="quotes-container">
  <%= render "quotes/quotes" %>
</div>

<div class="snake-container">
  <%= render "snake" %>
</div>

<div class="snake-container-overlay">
</div>



<!-- Articles -->
<!-- <div class="articles-header feature-card-header">
	<span class="articles-text feature-card-header-text"> Resources </span>
</div> -->
<div class="articles-container feature-card">

	<div class="articles-header feature-card-header">
		<span class="articles-text feature-card-header-text"> Resources </span>
	</div>

	<div class="feature-card-content">
    <div class="article-form">
    	<%= link_to "Post an Article", new_article_path, id: "new_article", remote: true %>
    </div>
    <div class="article-feed">
    	<%= render 'articles/index' %>
    </div>
 	</div>

</div>



<!-- Goals -->

<div class="goals-container feature-card">
  <div class="goals-header feature-card-header">
		<span class="goals-text feature-card-header-text"> Goals </span>
	</div>
  <div class="feature-card-content">
    <div class="goal-form">
      <%= render "goals/goals_form" %>
    </div>
    <div class="goal-feed" %>
      <%= render "goals/index" %>
    </div>
	</div>
</div>

<!-- <div class="goals-header feature-card-header">
	<span class="goals-text feature-card-header-text"> Goals </span>
</div> -->

<!-- Stats -->

<div class="stats-container feature-card">
	<div class="stats-header feature-card-header">
		<span class="stats-text feature-card-header-text"> Stats </span>
	</div>
	<div class="feature-card-content">
  	<div class="goals-count">
      <%= render 'goals/goals_count' %> 
    </div>

    <div class="articles-count">
      <%= render 'articles/articles_count' %>
    </div>

    <div class="upvotes-count">
      <%= render 'upvotes/upvotes_count' %>
    </div>
  </div>
</div>